version: 2.1
orbs:
  cypress: cypress-io/cypress@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5
filters: &filters
  tags:
    only: /.*/

# setup environment
# move/confirm we're in the correct project location(working dir)
# check out code? 
# check cache, otherwise
# install cypress
# save cache
# run commands to assert project ran appropriately

  jobs:
    build:
      docker:
        - image: 'cimg/node:lts'

      steps:

        - run:
            name: "log dir before setting working_directory"
            # /home/circleci/project 👈 we're here
            working_directory: ~/repo
            command: ls -l

      # working_directory: ~/repo

        - run:
            name: "log dir after setting working_directory"
            # /home/circleci/project 👈 we're here
            working_directory: ~/repo/examples/yarn-install-project
            command: ls -l
        # - checkout
        #   - checkout:
        #      path: ~/repo

        # Download and cache dependencies
        # - restore_cache:
        #     keys:
        #       - v1-dependencies-{{ checksum "package.json" }}
        #       # fallback to using the latest cache if no exact match is found
        #       - v1-dependencies-

        - run: yarn install --frozen-lockfile

        # - save_cache:
            # paths:
            #   - node_modules
            # key: v1-dependencies-{{ checksum "package.json" }}

        # run tests!
        - run: yarn test
      
      # steps:
      #   - persist_to_workspace:
      #       root: /home/circleci
      #       paths:
      #         - project

        # - restore_cached_workspace
      
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - build:
          filters: *filters
      - cypress/run:
          working-directory: ~/project
          requires:
            - build
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: cypress-io/cypress
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - testing-kitchensink
          context: circleci-orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
