version: 2.1
orbs:
  cypress: cypress-io/cypress@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5
filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - cypress/run:
          filters: *filters
          name: Standard Npm Example
          working-directory: examples/npm-install
          cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/npm-install/package.json" }}
          post-install: "npm run postinstall"
      - cypress/run:
          filters: *filters
          name: Yarn Example
          working-directory: examples/yarn-install
          cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/yarn-install/package.json" }}
          package-manager: "yarn"
      - cypress/run:
          filters: *filters
          name: Custom Install Example
          working-directory: examples/custom-install
          install-command: npm run custom-install
          cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/custom-install/package.json" }}
      - cypress/run:
          filters: *filters
          name: Angular Application
          working-directory: examples/angular-app
          cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
          start-command: "npm run start"
      - cypress/run:
          filters: *filters
          name: Angular Application Component Testing
          working-directory: examples/angular-app
          cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
          cypress-command: "npx cypress run --component --parallel --record --browser=chrome"
          parallelism: 3
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: cypress-io/cypress
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - Standard Npm Example
            - Yarn Example
            - Custom Install Example
            - Angular Application
            - Angular Application Component Testing

          context: circleci-orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
# VS Code Extension Version: 1.5.1
