version: 2.1
orbs:
  cypress: cypress-io/cypress@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5
filters: &filters
  tags:
    only: /.*/

jobs:
  cloning-kitchensink:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Cloning kitchensink"
          working_directory: /tmp/kitchensink
          command: |
            git clone https://github.com/cypress-io/cypress-example-kitchensink.git .
            ls
  cypress/run:
    
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - cloning-kitchensink:
          filters: *filters
      - cypress/run:
          requires:
            - cloning-kitchensink
          working-directory: /tmp/kitchensink
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: cypress-io/cypress
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - cloning-kitchensink
            - cypress/run
          context: circleci-orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
