description: >
  Single Docker container used to run Cypress Tests
parameters:
  node-version:
    type: string
    default: "16.16"
    description: >
      The version of node you want to use
docker:
  - image: cimg/node:<< parameters.node-version >>-browsers
